### ISSUE TITLE
Topic selection

### ISSUE THREAD

**Issue by ZIBOWANGKANGYU** [UBC-MDS/DSCI522_Team_23#1]
This is a place to discuss topic selection, contract, code of conduct and etc.

**Comment by jiajie0225** [comment]
Hi guys, I found an open-source website that could provide us with insights on choosing our dataset. 
https://archive.ics.uci.edu/ml/index.php

There are some topics that I think are relevant to what we have learned and we could apply our knowledge to it. 
1. Prediction on forest fire 
https://archive.ics.uci.edu/ml/datasets/Forest+Fires

2. Prediction on wine quality 
https://archive.ics.uci.edu/ml/datasets/Wine+Quality

**Comment by ZIBOWANGKANGYU** [comment]
Hi Josh this is really a great source! I personally like the wine quality one since I guess the forest fire one would require some geo-spatial feature engineering and thus we probably cannot properly handle it now.

**Comment by elina-linglin** [comment]
Thank you for the great recommendations Josh! I personally like the wine quality analysis as it incorporates the two topics that we are currently learning: class imbalance and feature selection. And I believe this would allow us to gain some more hands-on practice.

**Comment by ZIBOWANGKANGYU** [comment]
@wangjc640 What do you think Jiacheng? Once we pick our data choice we can star working on other aspects of setting up our repository.

**Comment by wangjc640** [comment]
I think this looks great! Let’s use this data then!

**Comment by wangjc640** [comment]
Close issue from week1
