### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by ZIBOWANGKANGYU** [UBC-MDS/DSCI522_Team_23#2]
Everyone,

Now that we have identified the data that we are interested in, let us move to finish the tasks specified by Milestone 1. 

For your reference, [here](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md) are the requirements for Milestone 1. 

The requirements have **four aspects**, namely: 

1. Project set-up. 

2. Project proposal

3. Downloading and saving data using scripts

4. Exploratory data analyses

We are also expected to **1) fork from the main repository**, **2) frequently commit to Git**, and **3) Communicate using Github repo**. 

I am willing to take the initiative and work on part 1: project set-up. I think I can draft the majority of part 1, except for the team work contract part. I need your input in the following aspects:

a) What is the quality of work each team member expects from themselves and each other?

b) When are team members not available (e.g., evenings and Sundays because of family obligations).

Please let me know your input into the two points above through Slack. Also, I think you three can divide the rest 3 aspects (2, 3, and 4) and begin top draft. Please reply to this issue to share with everyone which part you want to draft and what input you need from other teammates.

**Comment by jiajie0225** [comment]
I can try working on the project proposal of section 2. I am just wondering where am I supposed to be writing it? Jupyter notebook? Words? Latex?

**Comment by ZIBOWANGKANGYU** [comment]
I guess we can use `.md` file when doing the initial drafting. But I believe Tiff and the TAs will be able to give us more guidance on this.

**Comment by ZIBOWANGKANGYU** [comment]
Hi everyone, I have created a pull request with my work for project setup part of our milestone. I have created a [pull request](https://github.com/UBC-MDS/DSCI522_Team_23/pull/3)so that you can review. Please tell me what you all think. I also need your input regarding:
a) What is the quality of work each team member expects from themselves and each other?
b) When are team members not available (e.g., evenings and Sundays because of family obligations).
Thanks!

**Comment by wangjc640** [comment]
I'm not available on Sunday. Other than that, I'm basically available all the time. If I'm late replying, that means I'm working on something else but you can always at me if the job is urgent.

**Comment by elina-linglin** [comment]
I will take section 3 then if Jiacheng is fine with section 4. @wangjc640

**Comment by ZIBOWANGKANGYU** [comment]
Prior to our submission of milestone 1, I will create a release.

**Comment by wangjc640** [comment]
Milestone 1 complete
