### ISSUE TITLE
Too many command line arguments in EDA.py

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI522_Team_23#29]
Too many command line arguments in EDA.py, there should just be one command-line arg path for the folder to write the figs to, and then they hard-code the fig names (or grab them from the column names). They are already hard coding them as command line args, but there are too many. If they want to stick to this approach, they should instead read in a file that has a list of the filenames to create.

**Comment by ZIBOWANGKANGYU** [comment]
Thank you, Tiff!
Everyone: I am updating EDA.py now. I will create a new single chart to include all 11 explanatory variables. This way, we can reduce the number of command-line arguments and make the code DRY.
