### ISSUE TITLE
Error interpretation

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI522_Team_23#31]
Context is needed for interpreting RMSE. Is an RMSE of 0.7 actually a large error here given that the scale is out of 10? Also, RMSE != accuracy (see RMSE/RMSPE and accuracy definitions). RMSE is a suitable measure for regression, whereas accuracy is a measure for classification.

**Comment by ttimbers** [comment]
Also, how are the scores at the bottom of the report different from those at the top? And what are the scores at the bottom of the report?

**Comment by jiajie0225** [comment]
Thanks for the clarification on accuracy. The score at the top of the report is on the test set, whereas the score at the bottom of the report is on the cross-validation set (validation set).
