### ISSUE TITLE
Violation of the golden rule

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI522_Team_23#32]
All model comparisons before you choose your one single final model should be done using cross-validation on the test set. You can compare CV errors between different model classes (e.g., k-nn and ridge). Do not compare test errors from two different models. Otherwise you run the risk of optimization bias where one model fortuitously performs well on the particular test set (but it may not necessarily be the best model in general).

**Comment by jiajie0225** [comment]
Alright. Thanks for the feedback. We will make sure the golden rule violation problem be solved before submission.
