### ISSUE TITLE
Chart not rendered 

### ISSUE THREAD

**Issue by wangjc640** [UBC-MDS/DSCI522_Team_23#4]
Hey guys,

Just did some EDA and pushed it to my branch, you're more than welcome to check if anything I did seems not correct. 

But the chart by Altair is not rendered. I think Joel mentioned this in his class, how do I solve this issue?

**Comment by ZIBOWANGKANGYU** [comment]
Save a vega-lite spec and a PNG blob for each plot in the notebook
`alt.renderers.enable('mimetype')`

**Comment by jiajie0225** [comment]
Hi JiaCheng, I supposed we need to fork our main repository and work on it and create a pull request on it. (If I am not wrong)
I see that you have created a branch on the main repo. Correct me if I am wrong.

**Comment by wangjc640** [comment]
Chart rendered
