### ISSUE TITLE
Peer review feedback

### ISSUE THREAD

**Issue by Tammy1128** [UBC-MDS/DSCI522_Team_23#49]
Hi, I would like to share some suggestions, and I hope that this can be useful to improve your group project.

Documentation:
> 1. I would like to suggest that please add a .gitignore file under the root of the repository to organize your project better.

Suggestions:
> 2. I would like to suggest that please update the README file usage about how you can use make commands related to the Makefile. 
> 3. I would like to suggest that please add a limitation part to your final report, and you can point out that you may need to use another model such as `SVR` to get a better prediction.

**Comment by elina-linglin** [comment]
Hi Tammy,

Thank you for your constructive feedbacks! 

Best regards，
Elina
