### ISSUE TITLE
Peer review feedback from Rachel Xu

### ISSUE THREAD

**Issue by rainbowxyt0305** [UBC-MDS/DSCI522_Team_23#51]
Dear friends,

Thanks for presenting this fabulous analysis which is absolutely intriguing to me to learn more about wine~ I enjoyed reading the reports and EDA you created and learned much from it. I would just add a few minor points that I hope can be helpful for you~

**Final report**
- Perhaps also include a .md file in your doc directory for an easier and quicker view/reference.
- Perhaps in the `Summary` section, the opening remark of `With the wine quality data, we are attempting to build a regression model to help us identify the best white and white variants of the Portuguese “Vinho Verde” wine.` could be more clear in terms of if the model is identifying `the best white` or 'the best wine' or 'the best white wine'?

**README**
- Perhaps no need to mention dealing with `missing values` in both the `Analysis` section and the `EDA` section - only mention in one section should be sufficient.

**EDA**
- Perhaps also include a correlation matrix that shows the correlations between all columns (including the target) to better understand the multicollinearity aspect that you mentioned you are interested in knowing.

**General**
- Perhaps talk a little about how using Regression models (k-nn, ridge) make sense for this multi-classification prediction task.

<3
Rachel

**Comment by jiajie0225** [comment]
Hi Rachel,

Thank you so much for your detailed feedback! Appreciate it.

Cheers,
Joshua
