### ISSUE TITLE
Peer review feedback from Yuyan Guo

### ISSUE THREAD

**Issue by yuyanguo** [UBC-MDS/DSCI522_Team_23#52]
Hi team,

I am Yuyan Guo. Your report looks wonderful. I have been enjoying reading through it. Please find my suggestion below:

1. README

- Maybe you can add some detailed explanation for the features as the features are very domain-specific. Personally, I don't know about those terminologies much, so for me it's a little bit hard to understand.

- For the EDA section, I don’t think you need to be specific to which python function/method you used to get those summary statistics. for example: data.info()

- Maybe have more description and motivation for the research problem in the README. 

2. Analysis

- Maybe you can carry out feature selection to see if you can improve the score and make the model more interpretable.

- Maybe use Ridge to show some feature importance to see which feature is more useful in the prediction.

- Try more models if you have time? K-NN in general is not that powerful.

3. EDA

- In the README, you mentioned that "Also, scatterplot will be used to show the relationship between two variables". But I did not see it in the report. In general, I think it's good to have some table or figures indicate the correlation between features and target.

4. Code

- Very clear and well-organized.

5. Communication

- Very clear and readable

Yuyan:)

**Comment by jiajie0225** [comment]
Hi Yuyan,

Thank you so much for your feedback! 

Cheers!
