### ISSUE TITLE
Peer Review feedback - Siqi Zhou

### ISSUE THREAD

**Issue by roycezhou** [UBC-MDS/DSCI522_Team_23#53]
Dear all,

Thanks for presenting this fabulous group project to me. I liked reading the reports you created and acquired much from it. I would just add a few points that you could consider to change if you like :)

- **Documentation**: Overall, yes it is great! I noticed there is just no .md file available under /doc folder. To render a .md file might be helpful and more user-friendly when opening it from the GitHub website. 

- **Code**: The code is readable, clear, and with appropriate comments inside. 

- **Analysis and reasoning**: Yes it is great. I think you've done a great job! Perhaps you could utilize forward selection to reduce the number of features to enhance your model in future work. 

- **Communication**: Yes, it's easy to follow and the report communicates the findings effectively. Well done!

- **Suggestions**: Perhaps remove the .ipynb_checkpoints folder under /src? My suggestion is to create a .gitignore file to exclude those files to be pushed to your repo.

BRs,
Siqi Zhou

**Comment by jiajie0225** [comment]
Hi Siqi,

Thank you so much for your feedback!
